### PR TITLE
telephone-number-validator

### PR DESCRIPTION
**Pull request by Nooria150**
Implementing a telephone number validator using HTML, CSS, and JavaScript.

Added HTML structure for input form and result display.
Styled interface with CSS for improved user experience.
Implemented JavaScript validation logic for US phone numbers.

Manually tested input validation with various phone number formats.

Please review the JavaScript validation logic and CSS styling for consistency and efficiency.

### CODE REVIEW

**Comment by Nooria150** [comment]
@imfarhatsharefi @saqibi4213
could you please review my project.

**Comment by Nooria150** [comment]
@iamfarhatsharefi 
could you please give me feedback.

**Comment by iamfarhatsharefi** [comment]
@Nooria150 your hard working is admirable dear nooria, but following error is showing on your code and dont pass the freecodecamp. 
without entering a value into the #user-input element, an alert should appear with the text "Please provide a phone number"


otherwise you have a great design and a clean code.

**Comment by Saqibi4213** [comment]
> @imfarhatsharefi @Saqibi4213 could you please review my project.
dear @Nooria150 
- your code is not clear yet make sure you clear your code 
- you did not pass all instructions of freecodecamp work on it 
- and your code is still have some issue fix that your project dont show  anything 
Screenshot (39)

**Comment by Nooria150** [comment]
@Saqibi4213 @iamfarhatsharefi 
thank you for the feedback. I implemented the feedback. just left the deploy problem. after merging i will add deploy. it could solve my problems.

**Comment by iamfarhatsharefi** [comment]
@Nooria150 
🌞
🎉 Great Design Implemented


✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line

✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive   
And it will be great to make your deployment after the merge

**Comment by Saqibi4213** [comment]
🎉 Great Design Implemented 

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Git flow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line

✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your design is responsive
And it will be great to make your deployment after the merge
@Nooria150

**Review by ahzamir — APPROVED** [review]
### Hi @Nooria150  🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by ahzamir** [comment]
@Nooria150 @iamfarhatsharefi @Saqibi4213 

- **Great teamwork and impressive discussion throughout this project I liked it. ✅👍🎉🎯**

**Pull request merged**
